## README at: https://github.com/devcontainers/templates/tree/main/src/alpine
FROM mcr.microsoft.com/devcontainers/base:bullseye

RUN apt update
RUN apt upgrade -y
RUN apt install -y pkg-config bash-completion

USER vscode

## Install rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/home/vscode/.cargo/bin:${PATH}"

## Prepare to develop wasm applications
RUN rustup target add wasm32-unknown-unknown

## Use old trunk because more recent version does something wrong with integrity hashes?
RUN cargo install --locked trunk
