name: Build and Publish
on:
  push: 
    branches:
      - main
  
      # Allow running workflow manually
  workflow_dispatch:
  
# Set permissions of the GITHUBU_TOKEN to allow deployment to github pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      concurrency: ci-${{github.ref}}
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Rust setup
          uses: hecrj/setup-rust-action@v2
          with:
            targets: wasm32-unknown-unknown

        - name: Trunk setup
          run: cargo install --locked trunk
        
        - name: Build
          run: trunk build --release

        - name: Setup Pages
          uses: actions/configure-pages@v3

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2
          with:
            # Upload the public directory
            path: './dist'

        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2
